first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
middle_name = input("Enter middle name: ")
birthday = input("Enter birthday (YYYY-MM-DD): ")
gender = input("Enter gender: ")
address = input("Enter address: ")
course = input("Enter course: ")
year_level = input("Enter year level: ")

print("\nEntered Information:")
print("First Name:", first_name)
print("Last Name:", last_name)
print("Middle Name:", middle_name)
print("Birthday:", birthday)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year Level:", year_level)
